version: "3.9"

services:
    app:
        build: ./app
        container_name:  app
        restart: always
        ports:
            - "5000:5000"
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        expose:
            - 80
        environment:
            - NGINX_PORT=80
    db:
        image: postgres
        restart: always
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: doomanoid_user
            POSTGRES_PASSWORD: doomanoid_password
        ports:
            - "5432:5432"





