version: "3.3"

services:
    app:
        build: ./doomanoid
        container_name:  app
        restart: always
        ports:
            - "5000:5000"
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        expose:
            - 80
        environment:
            - NGINX_PORT=80
    db:
        image: postgres
        restart: always
        volumes:
            - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - APP_DB_USER=doomanoid_user
            - APP_DB_PASS=doomanoid_password
            - APP_DB_NAME=doomanoid
        ports:
            - "5432:5432"





