arkanoidConfig = {
    "IMG_STATIC_URL": "/static/images/arkanoid/",
    "SOUND_STATIC_URL": "/static/sound/",
    "PADDLE_WIDTH": 100,
    "PADDLE_HEIGHT":  20,
    "BRICK_WIDTH": 80,
    "BRICK_HEIGHT": 50,
    "BRICK_OFFSET_Y": 45,
    "FIRST_BRICK_OFFSET_X": 40,
    "TOP_LEVEL_BRICK_OFFSET_Y": 60,
    "BRICK_OFFSET_X": 10,
    "PADDLE_COLOR": "#4B4B4B",
    "CANVAS_WIDTH": 800,
    "CANVAS_HEIGHT": 600,
    "OFFSET_X": 15,
    "OFFSET_Y":  5,
    "PADDLE_SPEED": [8, 3],
    "BALL_RADIUS": 15,
    "BALL_HP": 10,
    "BONUS_RADIUS": 12,
    "BONUS_DELAY": 500,
    "FALLING_SPEED": 0.05,
    "BALL_SPEED": 5,
    "FRICTION": 0.2,
    "BALL_DAMAGE": 10,
    "LIVES": 3,
    "PADDLE_ZONE": 150,
    "FPS": 60
}